이 코드의 문서 : https://www.notion.so/GEARS-perturb-seq-bc7280ec1fad407291d6f8145df9c068?pvs=4

In [2]:
import scanpy
import pandas as pd

In [2]:
filtered = scanpy.read_mtx("/home/hb/python/ssd/lof/data/norman/GSE133344_filtered_matrix.mtx")
print(filtered)
filtered.to_df()

AnnData object with n_obs × n_vars = 33694 × 111668

In [38]:
import pandas as pd

def load_info(dir_path, geo_id, filtered, load_matrix=False):

    barcode_path = f'{dir_path}/{geo_id}_{filtered}_barcodes.tsv'
    cell_identites = f'{dir_path}/{geo_id}_{filtered}_cell_identities.csv'
    genes = f'{dir_path}/{geo_id}_{filtered}_genes.tsv'
    matrix = f'{dir_path}/{geo_id}_{filtered}_matrix.mtx'

    barcode = pd.read_csv(barcode_path, sep='\t', header=None, names=['cell_barcode'])
    cell_identities = pd.read_csv(cell_identites, sep=',', header=None)
    genes = pd.read_csv(genes, sep='\t', header=None)
    if load_matrix:
        matrix = scanpy.read_mtx(matrix)
    else:
        matrix = None
    return barcode, cell_identities, genes, matrix

In [39]:
barcode, cell_identites, genes, matrix = load_info('/home/hb/python/ssd/lof/data/norman','GSE133344', 'filtered')

/tmp/ipykernel_2287568/2797611796.py:11: DtypeWarning: Columns (2,3,4,5,6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  cell_identities = pd.read_csv(cell_identites, sep=',', header=None)

In [40]:
cell_identites.columns = cell_identites.iloc[0]
cell_identites = cell_identites[1:]
cell_identites

,cell_barcode,guide_identity,read_count,UMI_count,coverage,gemgroup,good_coverage,number_of_cells
1,TTGAACGAGACTCGGA-2,ARID1A_NegCtrl0__ARID1A_NegCtrl0,28684,1809,15.856274184632394,2,True,1
2,CGTTGGGGTGTTTGTG-7,BCORL1_NegCtrl0__BCORL1_NegCtrl0,18367,896,20.498883928571427,7,True,1
3,GAACCTAAGTGTTAGA-6,FOSB_NegCtrl0__FOSB_NegCtrl0,16296,664,24.542168674698797,6,True,1
4,CCTTCCCTCCGTCATC-4,SET_KLF1__SET_KLF1,16262,850,19.131764705882354,4,True,1
5,TCAATCTGTCTTTCAT-2,OSR2_NegCtrl0__OSR2_NegCtrl0,16057,1067,15.048734770384256,2,True,2
...,...,...,...,...,...,...,...,...
111441,TTTGCGCAGTCATGCT-2,RHOXF2_NegCtrl0__RHOXF2_NegCtrl0,1,1,1.0,2,False,0
111442,TTTGCGCCAGGACCCT-3,BCL2L11_BAK1__BCL2L11_BAK1,1,1,1.0,3,False,0
111443,TTTGCGCGTACTTGAC-3,CNN1_NegCtrl0__CNN1_NegCtrl0,1,1,1.0,3,False,0
111444,TTTGCGCTCTCGCATC-6,CEBPB_OSR2__CEBPB_OSR2,1,1,1.0,6,False,0
111445,TTTGGTTGTTCCGTCT-2,MAP2K3_MAP2K6__MAP2K3_MAP2K6,1,1,1.0,2,False,0

In [30]:
matrix.var = barcode
matrix.obs = genes
matrix.var_names = barcode['cell_barcode']
matrix.obs_names = genes[0]
# exp = matrix.to_df().T
# exp.describe()

,ENSG00000243485,ENSG00000237613,ENSG00000186092,ENSG00000238009,ENSG00000239945,ENSG00000239906,ENSG00000241599,ENSG00000279928,ENSG00000279457,ENSG00000228463,...,ENSG00000277196,ENSG00000277630,ENSG00000278384,ENSG00000278633,ENSG00000276345,ENSG00000277856,ENSG00000275063,ENSG00000271254,ENSG00000277475,ENSG00000268674
count,111668.000000,111668.0,111668.0,111668.000000,111668.000000,111668.0,111668.000000,111668.000000,111668.000000,111668.000000,...,111668.0,111668.0,111668.000000,111668.000000,111668.000000,111668.0,111668.0,111668.000000,111668.0,111668.0
mean,0.000260,0.0,0.0,0.002391,0.000090,0.0,0.000009,0.000107,0.694801,0.173828,...,0.0,0.0,0.093124,0.000009,0.729636,0.0,0.0,0.105285,0.0,0.0
std,0.016111,0.0,0.0,0.048994,0.009462,0.0,0.002993,0.010365,0.929045,0.425534,...,0.0,0.0,0.308728,0.002993,0.920920,0.0,0.0,0.334321,0.0,0.0
min,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0
25%,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0
50%,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0
75%,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,...,0.0,0.0,0.000000,0.000000,1.000000,0.0,0.0,0.000000,0.0,0.0
max,1.000000,0.0,0.0,2.000000,1.000000,0.0,1.000000,1.000000,16.000000,5.000000,...,0.0,0.0,3.000000,1.000000,8.000000,0.0,0.0,4.000000,0.0,0.0

In [41]:
cell_identites_filtered = cell_identites[cell_identites['good_coverage']!=False]

In [42]:
cell_identites_filtered['condition'] = cell_identites_filtered['guide_identity'].apply(lambda x: x.split('__')[0])

/tmp/ipykernel_2287568/3707520943.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cell_identites_filtered['condition'] = cell_identites_filtered['guide_identity'].apply(lambda x: x.split('__')[0])

In [37]:
norman.obs['condition'].value_counts()

control               5162
NegCtrl10_NegCtrl0    3325
NegCtrl11_NegCtrl0    2696
CEBPE_RUNX1T1         1135
KLF1_NegCtrl0         1120
                      ...
CBL_UBASH3A             56
C3orf72_FOXL2           55
CEBPB_CEBPA             55
JUN_CEBPB               54
JUN_CEBPA               51
Name: condition, Length: 286, dtype: int64

In [43]:
ctrl = cell_identites_filtered[cell_identites_filtered['condition'].isin(['NegCtrl10_NegCtrl0', 'NegCtrl11_NegCtrl0','NegCtrl0_NegCtrl0','NegCtrl1_NegCtrl0', 'NegCtrl0_NegCtrl1', 'NegCtrl1_NegCtrl1'])]
ctrl['condition'] = 'control'
ptb = cell_identites_filtered[~cell_identites_filtered['cell_barcode'].isin(ctrl.cell_barcode)]
assert len(cell_identites_filtered) == len(ptb) + len(ctrl)

/tmp/ipykernel_2287568/3287628626.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ctrl['condition'] = 'control'

In [46]:
cell_info = pd.concat([ctrl, ptb], ignore_index=True)
cell_info.condition.value_counts()

control            11183
CEBPE_RUNX1T1       1135
KLF1_NegCtrl0       1120
TBX3_TBX2           1094
SLC4A1_NegCtrl0      937
                   ...
CBL_UBASH3A           56
C3orf72_FOXL2         55
CEBPB_CEBPA           55
JUN_CEBPB             54
JUN_CEBPA             51
Name: condition, Length: 284, dtype: int64

In [47]:
cell_info = pd.concat([ctrl, ptb], ignore_index=True)
cell_info.to_csv('/home/hb/python/ssd/lof/data/norman/pre_processing/cell_info.csv', index=False)

In [89]:
exp_filtered.to_pickle("/home/hb/python/ssd/lof/data/norman/pre_processing/exp_filtered.pkl")

In [48]:
import numpy as np 
import pandas as pd
from scipy.sparse import csr_matrix
import scanpy
import anndata as ad

cell_info = pd.read_csv('/home/hb/python/ssd/lof/data/norman/pre_processing/cell_info.csv')
genes = pd.read_csv("/home/hb/python/ssd/lof/data/norman/GSE133344_filtered_genes.tsv", sep='\t', header=None, names=['gene_id', 'gene_symbol'])
expp = pd.read_pickle("/home/hb/python/ssd/lof/data/norman/pre_processing/exp_filtered.pkl")

In [49]:
cell_info.index = cell_info['cell_barcode']
genes.index = genes['gene_id']
del genes['gene_id']
del cell_info['cell_barcode']

In [58]:
cell_info.sort_index(inplace=True)
expp.sort_index(inplace=True)

In [59]:
expp

,ENSG00000243485,ENSG00000237613,ENSG00000186092,ENSG00000238009,ENSG00000239945,ENSG00000239906,ENSG00000241599,ENSG00000279928,ENSG00000279457,ENSG00000228463,...,ENSG00000277196,ENSG00000277630,ENSG00000278384,ENSG00000278633,ENSG00000276345,ENSG00000277856,ENSG00000275063,ENSG00000271254,ENSG00000277475,ENSG00000268674
cell_barcode,,,,,,,,,,,,,,,,,,,,,
AAACCTGAGAAACCAT-2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACCTGAGAAACCGC-6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACCTGAGAAAGTGG-8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
AAACCTGAGAAGAAGC-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACCTGAGAAGGTTT-7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGTCATCTTATCTG-5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,6.0,0.0,0.0,1.0,0.0,0.0
TTTGTCATCTTGCATT-7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
TTTGTCATCTTGTACT-5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
TTTGTCATCTTGTCAT-6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TTTGTCATCTTTAGTC-6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [60]:
adata = ad.AnnData(X=expp, obs=cell_info, var=genes)

In [61]:
import hdf5plugin
adata.write_h5ad(
    "/media/hdd/hb/lof/perturb_seq/raw_preprocessing/norman.h5ad",
    compression=hdf5plugin.FILTERS["zstd"]
)

In [62]:
norman = ad.read_h5ad("/media/hdd/hb/lof/perturb_seq/raw_preprocessing/norman.h5ad")

In [64]:
norman.obs.condition.unique()

['CEBPB_NegCtrl0', 'FEV_CBFA2T3', 'TGFBR2_IGDCC3', 'control', 'SNAI1_NegCtrl0', ..., 'CEBPB_OSR2', 'ZBTB10_SNAI1', 'ZBTB10_ELMSAN1', 'SAMD1_TGFBR2', 'CEBPB_CEBPA']
Length: 284
Categories (284, object): ['AHR_FEV', 'AHR_KLF1', 'AHR_NegCtrl0', 'ARID1A_NegCtrl0', ..., 'ZC3HAV1_NegCtrl0', 'ZNF318_FOXL2', 'ZNF318_NegCtrl0', 'control']